// pub mod day1;
// pub mod day2;
// pub mod day3;
// pub mod day4;
// pub mod day5;
// pub mod day6;
// pub mod day7;
// pub mod day8a;
// pub mod day8b;
// pub mod day9a;
// pub mod day9b;
// pub mod day10a;
// pub mod day10b;
// pub mod day11a;
// pub mod day11b;
// pub mod day12a;
// pub mod day12b;
// pub mod day13a;
// pub mod day13b;
// pub mod day14a;
// pub mod day14b;
// pub mod day15a;
// pub mod day15b;
// pub mod day16a;
// pub mod day16b;
// pub mod day17a;
// pub mod day17b;
// pub mod day18a;
// pub mod day18b;
pub mod day19a;

pub type AoCResult<T> = Result<T, Box<dyn std::error::Error>>;
